[variables]
PYTHONPATH = '/app'

[providers]
python = "3.11"

[phases.setup]
nixPkgs = ['python311', 'pip', 'gcc']
nixLibs = ['stdenv.cc.cc.lib']

[phases.install]
dependsOn = ['setup']
cmds = [
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1' 