[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
# Environment variables will be set in Railway dashboard
# MONGODB_URL
# SECRET_KEY  
# FRONTEND_URL
PYTHONPATH = "/app"